# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'

target 'Desafiodti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desafiodti
	pod 'Alamofire', '~> 5.7'

  target 'DesafiodtiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DesafiodtiUITests' do
    # Pods for testing
  end

end
